### PR TITLE
Mg/setup measurement error

### LINKED ISSUE #10: Potential timing issue
**Describe the bug**
Hey - this may be correct as long as i read rust code correctly, i'm coding in other languages. Please excuse me if the text below is not correct.

In https://github.com/EmbarkStudios/tiny-bench/blob/main/tiny-bench/src/benching.rs#L228-L230 i see the following:

```rust
let start = Instant::now();
black_box((closure)(input));
elapsed += Instant::now().duration_since(start);
```

which, to me, seems to be timing every invocation of the benched code. The potential issue here is that the timer call contains overhead by itself (significant compared to really small operations): the captured value would contain the timing of Instant::now after it acquired the timestamp, then the benchmark itself, then the timing of Instant::now before it acquires the timestamp, skewing the results; as for now, i have just a single silly example obtained on a single machine, but there it took 55-60ns. If, for example, two benchmarks take 5 and 10ns respectively, and the timer call takes 55ns, then the 100% difference will convert into only into ~8.33%. So i think it is worth to run a number of internal wrapping iterations, with every wrapping iteration running looping for a predefined / configuration number (sadly i can't provide a decent one), and collect the timing at the boundaries of such a wrapping iteration. It would also help to provide some statistics on the variance / standard deviation - while by itself it usually doesn't apply to tight code samples, high values would tell end user that there is something wrong with the setup (e.g. chrome running in background).

### PR DESCRIPTION
**Pull request by MarcusGrass**
### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

1. Reduce measument error on benches with a setup, clean up lints, fixup deny.toml
2. Ceil calculated iterations to 5B, otherwise the number of iterations can approach infinity and the bench would never complete

### Related Issues

Fixes https://github.com/EmbarkStudios/tiny-bench/issues/10

### CODE REVIEW

File: tiny-bench/src/benching.rs [hunk 1]
```diff
@@ -86,12 +86,15 @@ pub fn bench_with_configuration_labeled<T, F: FnMut() -> T>(
 
 fn calculate_iters_and_total_iters(
     cfg: &BenchmarkConfig,
-    mean_execution_time: f64,
+    mut mean_execution_time: f64,
```
Comment (jnises) [inline tiny-bench/src/benching.rs:89]: call the argument `mean_execution_time_ns`?

**Review by jnises — APPROVED** [review]
looks good

**Comment by MarcusGrass** [comment]
@jnises Thanks, could you have another quick peek at the last commit? Realized it's pretty easy to batch and prevent the ram explosion. It didn't affect the measurement overhead in any noticable way either

**Review by jnises — APPROVED** [review]
